### ISSUE TITLE
Readme.md error

### ISSUE THREAD

**Issue by jamesatwork** [tlongren/docker-wordpress-nginx-ssh#6]
Hello, tlongren

In the Install section of readme,

If you'd like to build the image yourself:

$ git clone https://github.com/tlongren/docker-wordpress-nginx-ssh.git
$ cd docker-wordpress-nginx-ssh
$ sudo docker build -t="tlongren/docker-wordpress-nginx-ssh"

The last line should be:
$ sudo docker build -t="tlongren/docker-wordpress-nginx-ssh" .

There are maybe lost a "." in the command. Could you check it? 

And a lots of  thank for the work!

Regards,
James

**Comment by tlongren** [comment]
Fixed. Thanks, @jamesatwork!
