### ISSUE TITLE
MySQLWorkbench

### ISSUE THREAD

**Issue by bigburchbaby** [tlongren/docker-wordpress-nginx-ssh#8]
This image is great!  I wanted to know if there is any good way to use a 3rd party database tool like MySQLWorkbench with this running container?  I am currently having trouble accessing the MySQL tables within the image

**Comment by tlongren** [comment]
Been a while since I've touched this but an SSH tunnel may work (I think MySQL workbench has an option for it). Or maybe something like [sshuttle](https://github.com/sshuttle/sshuttle).
