### ISSUE TITLE
sudo pass

### ISSUE THREAD

**Issue by Jdesk** [tlongren/docker-wordpress-nginx-ssh#9]
what's the default sudo password inside container  (can't do a thing without sudo) and definitely don't have a password for the user (wordpress).

**Comment by zatarra** [comment]
I did a small modification to this container's settings and added sudo access to user wordpress. Feel free to pull zatarra/docker-wordpress-nginx-ssh

Or you can simply build it from the sources ( https://github.com/zatarra/docker-wordpress-nginx-ssh )

All credits go to tlongren. All I did was to add sudo access.

**Comment by tlongren** [comment]
@zatarra, thanks! I added sudo access for the wordpress user to this repo as well.
